### ISSUE TITLE
Hide expired codes

### ISSUE THREAD

**Issue by nickmccurdy** [LaustinSpayce/arena-codes#14]
I've noticed that `RepairAndRecharge` and the older card style codes are still displayed on the website, despite having expired already. It would be great if we could remove codes with dates that have passed automatically. I'd also recommend scheduling your deploys so you don't have to remember to redeploy after a code expires (examples: [Netlify](https://www.netlify.com/blog/how-to-schedule-deploys-with-netlify/), [GitHub Actions](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule)).

**Comment by LaustinSpayce** [comment]
It’s a good idea, I just cleaned some up. It does seem that WOTC will be retiring sending out codes in favor of the new inbox system they have so I’m fine just tidying up codes myself as they do slowly expire.
